name: imageurlviewer
description: "A Flutter project to view images from URLs with web support."

# Prevent accidental publishing to pub.dev
publish_to: 'none'

# Versioning
version: 1.0.0+1

# Environment constraints
environment:
  sdk: '>=3.5.4 <4.0.0'  # Updated SDK constraint for better compatibility

# Dependencies
dependencies:
  flutter:
    sdk: flutter

  # Flutter web plugins (required for web support)
  flutter_web_plugins:
    sdk: flutter

  # Cupertino Icons for iOS-style icons
  cupertino_icons: ^1.0.8

  # URL Launcher for opening URLs (supports web)
  url_launcher: ^6.2.2
  url_launcher_web: ^2.0.20  # Web implementation for url_launcher

  # Provider for state management
  provider: ^6.1.1

  # HTTP package for network requests
  http: ^1.2.0

  # Cached Network Image for efficient image loading
  cached_network_image: ^3.3.0

  # Flutter Toast for displaying toast messages
  fluttertoast: ^8.2.2

# Dev dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter

  # Flutter Lints for improved code quality
  flutter_lints: ^4.0.0

  # Build Runner for code generation (if needed)
  build_runner: ^2.4.6

# Flutter-specific configuration
flutter:
  uses-material-design: true

  # Assets (uncomment and add your assets here)
  # assets:
  #   - images/logo.png

  # Fonts (uncomment and add your custom fonts here)
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700